# Generated by Django 5.0 on 2023-12-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shortenedurl_has_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='visitors',
            field=models.IntegerField(default=0),
        ),
    ]
